defaults: &defaults
  adapter: mysql
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  host: localhost

development:
  database: blog_development
  <<: *defaults

test:
  database: blog_test
  <<: *defaults

production:
  database: blog_production
  <<: *defaults
